from ListPractice import removeEvenInt
from ListPractice import merge_two_sorted_list
from ListPractice import two_number_add_to_k
from ListPractice import multiply_all_values_in_list
from ListPractice import maximum_val_list
